In [2]:
import pickle
from dataReader import *
import re

C:\ProgramData\Anaconda3\lib\site-packages\tqdm\autonotebook\__init__.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  " (e.g. in jupyter console)", TqdmExperimentalWarning)


In [59]:
import numpy as np
from sklearn.cluster import SpectralClustering
from sklearn.cluster import KMeans

In [3]:
with open('../data/processed/movies.pkl', 'rb') as movies_pkl:
    movies = pickle.load(movies_pkl)

In [30]:
t = movies[162].lang
t

'en'

In [15]:
def returnGenre(s):
    p = re.finditer(r'name', s)
    position = [m.start(0) for m in p]
    allGenres = set()
    for pos in position:
        genre = ''
        for i in range(pos+8, len(s)):
            if s[i] == '\'':
                break
            genre += s[i]
        allGenres.add(genre)
    return allGenres

In [16]:
returnGenre('[{\'id\': 18, \'name\': \'Drama\'}, {\'id\': 80, \'name\': \'Crime\'}]')

{'Crime', 'Drama'}

In [43]:
uniqueGenres = set()
uniqueLanguages = set()

for movie in movies:
    uniqueGenres.update(returnGenre(movie.genres))
    if isinstance(movie.lang, str):
        uniqueLanguages.add(movie.lang)
print (uniqueGenres)       
print (uniqueLanguages)

{'Comedy', 'Documentary', 'History', 'Mystery', 'Thriller', 'Foreign', 'War', 'Animation', 'Crime', 'Action', 'Horror', 'Science Fiction', 'Romance', 'Adventure', 'Fantasy', 'Family', 'Western', 'TV Movie', 'Music', 'Drama'}
{'bm', 'id', 'sh', 'he', 'ky', 'ko', 'ml', 'hr', 'la', 'eo', 'bs', 'tg', 'ar', 'sl', 'mk', 'el', 'kn', 'zh', 'lt', 'nb', 'wo', 'qu', 'sv', 'mt', 'en', 'ru', 'cs', 'ps', 'fi', 'am', 'ms', 'fr', 'ro', 'hi', 'mr', 'fy', 'tr', 'ja', 'th', 'eu', 'ka', 'ay', 'ca', 'si', 'jv', 'cn', 'zu', 'tl', 'pa', 'is', 'iu', 'ne', 'ta', 'kk', 'xx', 'ab', 'de', 'pt', 'lb', 'bo', 'pl', 'te', 'sm', 'es', 'sr', 'bn', 'mn', 'hu', 'it', 'sq', 'cy', 'gl', 'lv', 'et', 'vi', 'rw', 'bg', 'no', 'lo', 'hy', 'fa', 'sk', 'uk', 'ur', 'da', 'nl', 'af', 'ku', 'uz'}


In [48]:
uniqueGenresDict = {k: v for v, k in enumerate(list(uniqueGenres))}
uniqueLanguagesDict = {k: v for v, k in enumerate(list(uniqueLanguages))}

In [75]:
X = []
for movie in movies:
    if not isinstance(movie.lang, str):
        language = len(uniqueLanguagesDict)
    else:
        language = uniqueLanguagesDict[movie.lang]
    revenue = movie.revenue
    vote = movie.vote_average
    num_female = len(movie.cast.get_female_cast())
    num_male = len(movie.cast.get_male_cast())
    genres = returnGenre(movie.genres)
    for g in genres:
        genre = uniqueGenresDict[g]
        line = [language, revenue, vote, num_female, num_male, genre]
    X.append(line)
        
print(X)

[[28, 0, 7.1, 0, 1, 8], [28, 0, 7.1, 1, 4, 0], [24, 4300000, 6.5, 14, 8, 8], [24, 12136938, 6.4, 3, 9, 9], [24, 775398007, 8.1, 3, 47, 9], [24, 940335536, 7.6, 5, 16, 15], [24, 677945399, 8.2, 7, 35, 19], [24, 356296601, 7.9, 22, 15, 19], [24, 23217674, 8.0, 11, 42, 3], [24, 40031879, 7.7, 5, 11, 18], [24, 0, 5.6, 3, 3, 3], [24, 263920180, 7.3, 8, 32, 11], [56, 650422, 8.0, 4, 11, 11], [24, 9726954, 7.2, 6, 4, 12], [24, 0, 7.8, 0, 2, 1], [24, 655011224, 7.5, 5, 30, 14], [24, 180949000, 7.7, 9, 11, 9], [24, 96889998, 6.6, 1, 15, 6], [3, 0, 6.5, 2, 5, 19], [24, 1574623, 5.1, 1, 2, 18], [24, 89460381, 8.0, 4, 27, 6], [37, 0, 7.9, 0, 1, 7], [24, 159157447, 7.7, 5, 19, 16], [24, 527068851, 6.9, 7, 9, 15], [24, 72258126, 7.9, 6, 10, 11], [63, 20908467, 7.6, 6, 11, 4], [24, 1065659812, 7.0, 4, 26, 14], [24, 60740827, 6.9, 2, 11, 8], [24, 68700000, 7.9, 5, 12, 13], [24, 168840000, 7.4, 13, 42, 11], [63, 51001550, 7.5, 8, 4, 12], [24, 215000000, 6.8, 3, 8, 19], [24, 50068310, 6.4, 4, 7, 8], [24

In [76]:
X = np.array(X)

In [79]:
len(X)

46628

In [77]:
# clustering = SpectralClustering(n_clusters=5).fit(X)
clustering = KMeans(n_clusters=20).fit(X)


In [82]:
type(clustering.labels_)

numpy.ndarray

In [91]:
len(clustering.labels_)

46628

In [114]:
allData = np.c_[X,clustering.labels_]
allData

array([[2.8e+01, 0.0e+00, 7.1e+00, ..., 1.0e+00, 8.0e+00, 0.0e+00],
       [2.8e+01, 0.0e+00, 7.1e+00, ..., 4.0e+00, 0.0e+00, 0.0e+00],
       [2.4e+01, 4.3e+06, 6.5e+00, ..., 8.0e+00, 8.0e+00, 0.0e+00],
       ...,
       [2.8e+01, 0.0e+00, 0.0e+00, ..., 0.0e+00, 1.2e+01, 0.0e+00],
       [2.8e+01, 0.0e+00, 8.0e+00, ..., 1.0e+00, 1.2e+01, 0.0e+00],
       [5.7e+01, 0.0e+00, 0.0e+00, ..., 0.0e+00, 1.4e+01, 0.0e+00]])

In [98]:
len(allData[0])

7

In [111]:
labelGenre = {}
for row in allData:
    label = allData[6][0]
    if label in labelGenre:
        labelGenre[label].append(allData[5])
    else:
        labelGenre[label] = []

In [113]:
for label in labelGenre:
    print (label)

24.0


In [109]:
labelGenreDom = {}
for labelG in labelGenre:
    lst = list(labelGenre[labelG])
    print (lst)
    labelGenreDom[labelG] = max(set(lst), key=lst.count)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


TypeError: unhashable type: 'numpy.ndarray'

In [110]:
lst

[array([2.40000000e+01, 9.40335536e+08, 7.60000000e+00, 5.00000000e+00,
        1.60000000e+01, 1.50000000e+01, 1.90000000e+01]),
 array([2.40000000e+01, 9.40335536e+08, 7.60000000e+00, 5.00000000e+00,
        1.60000000e+01, 1.50000000e+01, 1.90000000e+01]),
 array([2.40000000e+01, 9.40335536e+08, 7.60000000e+00, 5.00000000e+00,
        1.60000000e+01, 1.50000000e+01, 1.90000000e+01]),
 array([2.40000000e+01, 9.40335536e+08, 7.60000000e+00, 5.00000000e+00,
        1.60000000e+01, 1.50000000e+01, 1.90000000e+01]),
 array([2.40000000e+01, 9.40335536e+08, 7.60000000e+00, 5.00000000e+00,
        1.60000000e+01, 1.50000000e+01, 1.90000000e+01]),
 array([2.40000000e+01, 9.40335536e+08, 7.60000000e+00, 5.00000000e+00,
        1.60000000e+01, 1.50000000e+01, 1.90000000e+01]),
 array([2.40000000e+01, 9.40335536e+08, 7.60000000e+00, 5.00000000e+00,
        1.60000000e+01, 1.50000000e+01, 1.90000000e+01]),
 array([2.40000000e+01, 9.40335536e+08, 7.60000000e+00, 5.00000000e+00,
        1.60000000